services:
  ubuntu:
    image: darlon/iftech:contador
    container_name: iftech-contador

  #docker run --name iftech-contador --rm -it darlon/iftech:contador
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    command: iftech-contador